### ISSUE TITLE
Update to last Gnome version

### ISSUE THREAD

**Issue by Lailah** [mariospr/text-scaler-gnome-shell-extension#3]
Hello!
I've been using your extension for quite a long time, in Fedora 24 and Fedora 25.  But now I made a fresh install  (F25 Workstation)  and I can't use this extension anymore.
Any plans of updating it to the last GTK/Gnome version?
Thanks!

**Comment by mariospr** [comment]
Sorry, I did not see this until now. Could you provide a few more details on what the problem exactly is? I'm using the extension in Fedora 25 without issues, and from your message I understand it used to work for you in F25 as well, but it stopped working after doing a fresh install. Is that correct?

Also, could you check if there's any error message in the Looking Glass console? Press Alt + F2 and then type "lg" and press ENTER to laungh the Looking Glass console, then click in the "Extensions" tab and check whether there's any error message in there. Thanks!
