### ISSUE TITLE
List with pre-defined scales

### ISSUE THREAD

**Issue by igordovgaluk** [mariospr/text-scaler-gnome-shell-extension#4]
could you please add a list with 2-3 values with predefined scale factors?

**Comment by mariospr** [comment]
Maybe. Care to develop a bit more how you would visualize that in the popup?

**Comment by igordovgaluk** [comment]
what about this one?
![image](https://user-images.githubusercontent.com/4215041/33823559-386d2d42-de64-11e7-9ff3-a64f5b6a120c.png)

the predefined values maybe be defined in the extension's config

**Comment by mariospr** [comment]
How would that work, specifically? Would those be buttons that you'd click on, with predefined values? In that case... how would you configure those predefined values (I'd rather avoid having to provide an additional configuration dialog, I like to keep the extension simple)? Or would they perhaps be text fields that react to events to set the slider when you click on them?

To be honest, I don't like that the proposed UI is giving the same importance to those widgets with the predefined values (which are optional to use) than to the text field showing the slider's current value. It seems to make the whole popup too crowded, at least to my eyes.

Not saying that the idea is bad, though, as someone who normally moves between 1.00, 1.10 and 1.15, I like having a way to  set 1-2 predefined values easily, but not at the expense of having an entire new row just for that.

Last, I'd like to point out that 1-2 defaults should be enough (and probably 1), 3 seems too many to me. And if it was only 1 default, that could be perhaps implemented as some sort of "Go back to previous value" functionality, for instance.
