### ISSUE TITLE
Not working on gnome 3.34 Ubuntu 19.10

### ISSUE THREAD

**Issue by foer** [mariospr/text-scaler-gnome-shell-extension#6]
The extension stops working on Ubuntu 19.10/Gnome 3.34 with the following error:

`Error: No signal 'value changed' on object 'Gjs_Slider'`

**Comment by mariospr** [comment]
I don't have a running GNOME 3.34 yet so I can't look into this properly right now, will have to wait until next month or so, once I upgrade. In the meantime, if anyone wanted to propose a patch I'd be happy to review it :smile:

**Comment by foer** [comment]
It is probably the same error and fix like here:

https://github.com/kiyui/gnome-shell-night-light-slider-extension/issues/48

**Comment by mariospr** [comment]
Nice! Since you already have the right environment for testing, would you care to prepare a patch, test it and create a pull request here that I can review and (potentially) merge? Thanks!

**Comment by foer** [comment]
> would you care to prepare a patch, test it and create a pull request here

I really would like to do so but i'am not familiar with javascript...

**Comment by mariospr** [comment]
> I really would like to do so but i'am not familiar with javascript...

Ok then. I'll try to come up with a patch at some point, but I'm afraid that it will have to wait a bit since I don't have a GNOME 3.34 running yet (and Ubuntu 19.10 hasn't come out yet either, actually today it's the day the Beta will be released), sorry about that.

**Comment by mariospr** [comment]
I've pushed a GNOME_3_34 branch that contains an updated version of extension.js that should work on Ubuntu 19.10 with GNOME 3.34, see it here: https://github.com/mariospr/text-scaler-gnome-shell-extension/blob/GNOME_3_34/extension.js

Please take a look and let me know whether that works for you if you have some time, thanks!

**Comment by foer** [comment]
It works perfekt now with ubuntu 19.10/gnome 3.34 without an error! Thanks a lot!

**Comment by mariospr** [comment]
Nice! Will release it in extensions.gnome.org then as a new version supporting 3.34 then. Thanks to you for reporting! (and for forcing me to look into this code again after neglecting it for a while! ;))

**Comment by mariospr** [comment]
FWIW: The new version of the extension has been published in https://extensions.gnome.org/extension/1018/text-scaler now (select 3.34 in the combo box)
