### ISSUE TITLE
add keyboard shortcuts

### ISSUE THREAD

**Issue by wbolster** [mariospr/text-scaler-gnome-shell-extension#7]
hi, thanks for this useful extension.

it would be nice if there was a way to have shortcut keys to avoid using the mouse.

gnome itself also has a accessibility keyboard shortcuts to increase/decrease the text scale, but the granularity is quite coarse (and hence not very useful for me (laptop vs external screen).

**Comment by mariospr** [comment]
Not planning to work on that, but patches would be welcome. Until then, closing this issue (feel free to reopen if suggesting a patch, though). Thanks
